version: '20.10'


services:
  redis:
    image: redis
    restart: always
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty

  postgres_admin:
    image: adminer
    restart: always
    ports:
      - 8001:8080

  main_api:
      restart: always
      build:
        context: ./WEBAPP
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      links:
        - postgres:postgres
      #command: ["python3", "./src/API/manage.py", "migrate"]
      #command: ["python3", "./src/API/manage.py", "runserver", "0.0.0.0:8000"]
      command: ["python3", "./src/API/manage.py", "runserver", "0.0.0.0:8000"]
      


  worker:
      restart: always
      build:
        context: ./WEBAPP
      command: ["celery", "--workdir=./src/API/", "-A", "main", "worker"]
